sudo: required
services:
  - docker

before_install:
  -docker build -t adpoyraz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adpoyraz/react-test npm test

after_success:
  - docker build -t adpoyraz/multi-client ./client
  - docker build -t adpoyraz/multi-nginx ./nginx
  - docker build -t adpoyraz/multi-server ./server
  - docker build -t adpoyraz/multi-worker ./worker

# log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

#Push images to Docker Hub
  - docker push adpoyraz/multi-client
  - docker push adpoyraz/multi-nginx
  - docker push adpoyraz/multi-server
  - docker push adpoyraz/multi-worker